# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

personality_types = PersonalityType.create(
  [{ type_name: 'Naturalist', type_description: "'Naturalists’…are attached to the natural world, frequently working with plans and animals in their environment. Often nature lovers, they like to experience the world outdoors. They are committed to preserving and protecting the planet and its natural resources. Serene, earthy, efficient and solid, they excel at working as one with the natural environment.", realsolution: "-Grow your own herb garden.-Take a screen free walk during your lunch break.-Volunteer at a local CSA.-Hike a new peak/walk a new trail each month." },
  { type_name: 'Mentor', type_description: "'Mentors'...are people-oriented.  They have great communication skills and are most fulfilled when assisting or working directly with others to improve a personal or societal situation.  Mentors are patient and compassionate and work best in a group or on a team toward a common goal.  Mentors excel at working with others to help them learn and grow.", realsolution: "-Volunteer pretty much anywhere (YMCA, political campaign, school). -Tutor someone (sibling/neighbor/coworker) for 30 mins. each week." },
  { type_name: 'Analyzer', type_description: "'Analyzers'...are inquisitive.  They delve, study and look deeply for information.  They have a keen eye and an experimental nature.  Analyzers use these capacities to figure out problems and search for the facts, often in a laboratory environment.  They excel at going beyond the surface toward uncovering information and discovery.", realsolution: "-Look around on stack exchange and try to answer at least one person's question.-Check out a new documentary on Netflix and talk to one person about your outlook on it." },
  { type_name: 'Inventor', type_description: "'Inventors'...are creative.  They take a contemporary, ???out of the box??? approach to work and life. Inventors use themselves and other medium, often various forms of the arts, to communicate and interact with the world.  Inventors excel when they are ???lost in their work,??? completely engrossed in a project.", realsolution: "-Spend two uninterrupted hours each week on your hobby. Give some suggestions.-Jot down a cool, unique work/invention/vacation/business idea each week.-Get up before the sun: spend 1 hour in the morning working on your thing before work, no distractions." },
  { type_name: 'Planner', type_description: "''Planners'...are the detail people.  They are methodical, precise, and detail-oriented.  Planners create systems to follow, and enjoy working with data, detail, words and numbers.  Great at manipulating data, they love procedure and routine.  Often found in office settings, they excel at completing detailed work in an organized manner.", realsolution: "-Start or join a fantasy sports league.-Clean up your email inbox, and keep it clutter-free.- Plan your weekends in advance to maximize their value.-Put yourself in a situation beyond your control, such as riding a roller coaster, once a month." },
  { type_name: 'Visionary', type_description: "'Visionaries'...are pioneers.  They are great convincers and like to work with others in a ???take charge??? capacity.  They love to take risks, make changes and set trends.  They tend to be   ambitious and energetic.  Visionaries are often in positions of prominence in business and the public eye and excel at taking charge and gaining the confidence of others.", realsolution: "-Start a blog to make weekly updates on your cool new shoes/great new site or app you found/latest book you read." },
  { type_name: 'Action Taker', type_description: "'Action-Takers'...are hands-on doers.  They use manual and physical skills, working with technology or machinery to complete tasks.  Often there is an athletic aspect to their work.  They are handy, practical, systematic, applied, and 'down-to-earth.'  They are drawn to jobs that involve a specific skill-set and a concrete task.  They excel at solitary, goal-oriented work and 'getting the job done.", realsolution: "-Finish all the books you start reading.-Learn a new skill such as painting to use your hands in a new way." }])
